.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HELLO" "1" "May 2015" "" ""
.
.SH "NAME"
\fBhello\fR \- greets bleh the world, or another arbitrary target
.
.SH "SYNOPSIS"
\fBhello\fR [\fItarget\fR]
.
.SH "DESCRIPTION"
hello(1) is a program that greets either
.
.IP "\(bu" 4
the entire world, if \fItarget\fR is not supplied, or
.
.IP "\(bu" 4
an arbitrary person, group, or other target\.
.
.IP "" 0
.
.SH "EXAMPLES"
To greet the entire world (note: the world\'s reciprocal behavior is undefined):
.
.br
hello
.
.P
To greet the reader of this post and make them feel welcome:
.
.IP "" 4
.
.nf

        hello
.
.fi
.
.IP "" 0
.
.P
\'Spin reader\'
.
.SH "DIAGNOSTICS"
Returns 0 on successful greeting\.
.
.SH "AUTHOR"
Matt Behrens \fImatt\.behrens@atomicobject\.com\fR
.
.SH "SEE ALSO"
goodbye(1) No newline at end of file
